
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#recorder:
#  purge_keep_days: 30  # 只保留最近 N 天的資料
#  auto_purge: true     # 每晚自動清理

automation: !include automations.yaml

script: !include scripts.yaml

scene: !include scenes.yaml

template: !include template.yaml

homeassistant:
  packages: !include_dir_named packages
